# import = ["~/.config/alacritty/themes/themes/gruvbox_material_medium_dark.toml"]
live_config_reload = true

[bell]
duration = 0

[cursor]
thickness = 0.15
unfocused_hollow = true
vi_mode_style = "Underline"

[cursor.style]
blinking = "Never"
shape = "Block"

[debug]
render_timer = false

[env]
TERM = "xterm-256color"

[font]
size = 15 

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[font.normal]
family = "SauceCodePro Nerd Font"
style = "Regular"

[mouse]
hide_when_typing = true

[scrolling]
history = 100000
multiplier = 3

[shell]
args = ["--login"]
program = "/bin/fish"

[window]
title = "alacritty"

[window.padding]
x = 0
y = 0
