#! /bin/sh

if xrandr | grep "DP-0 connected"; then
	bspc wm -O DP-0 HDMI-0
	bspc monitor DP-0 -d I II III IV V
	bspc monitor HDMI-0 -d VI VII VIII IX X
else
	bspc monitor -d I II III IV V VI VII VIII IX X
fi

bspc config normal_border_color  "#191724"
bspc config focused_border_color  "#908caa"
bspc config active_border_color "#524f67"

bspc config border_width         2
bspc config window_gap           0

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true


# java GUI support  
wmname LG3D &

pgrep -x sxhkd || sxhkd &
polybar &

$HOME/.config/polybar/launch.sh

# set background (root window) color & root cursor type
xsetroot -solid '#191724' -cursor_name left_ptr &

# disable black screen saver
xset -dpms &
xset s off &
# change cursor speed
xset r rate 150 35 &

bspc rule -a window desktop=^6
