#! /bin/sh

# mouse configuration 
# ~/.system/scripts/mouse.sh &

if xrandr | grep "DP-0 connected"; then
	bspc wm -O DP-0 HDMI-0
	bspc monitor DP-0 -d I II III IV V
	bspc monitor HDMI-0 -d VI VII VIII IX X
else
	bspc monitor -d I II III IV V VI VII VIII IX X
fi

bspc config normal_border_color  "#1e1e2e"
bspc config active_border_color  "#a6e3a1"
bspc config focused_border_color "#a6e3a1"

bspc config border_width         2
bspc config window_gap           0

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# java GUI support  
wmname LG3D &

# set background (root window) color & root cursor type
xsetroot -solid '#1E1E2E' -cursor_name left_ptr &

setxkbmap -option caps:escape,shift:both_capslock &

bspc rule -a window state=fullscreen desktop=^6

